### ISSUE TITLE
segmentation fault processing certain redirection operators

### ISSUE THREAD

**Issue by tomasohara** [clarity20/bash2py#6]
Bash2Py has a bug when handling certain types of redirection operators (e.g., >&2):

```
$ grep '>' ../tests/tests1/trap4.sub
    trap 'echo "in trap EXIT">&2' EXIT
    echo 'sleep 2'>&2
    echo 'wait $!'>&2
...

echo $'run ../tests/tests1/trap4.sub\nbt' | gdb bash2pyengine
...
Program received signal SIGSEGV, Segmentation fault.
0x0000555555594ba1 in make_redirection (source=..., instruction=r_duplicating_output, dest_and_filename=..., 
    flags=0) at make_cmd.c:920
920       temp->position =  dest_and_filename.filename->position;
(gdb) #0  0x0000555555594ba1 in make_redirection (source=..., instruction=r_duplicating_output, 
    dest_and_filename=..., flags=0) at make_cmd.c:920
#1  0x0000555555584bf0 in yyparse () at ./parse.y:663
#2  0x000055555558374e in parse_command () at eval.c:265
```

where ./parse.y:663 is from the following production:
```
	|	GREATER_AND NUMBER
			{
			  source.dest = 1;
			  redir.dest = VALUE($2);
			  $$ = make_redirection (source, r_duplicating_output, redir, 0);
			}
```

A fix for this is to make sure the WORD_DESC structure is completely initialized before invoking make_redirection. For example,

```
#if DUMMY_WORD_DESC
WORD_DESC dummy_word_desc = { "dummy", 0, {0, 0, 0} };
#endif

...

#if DUMMY_WORD_DESC
			  redir.filename = &dummy_word_desc;
#endif
			  $$ = make_redirection (source, r_duplicating_output, redir, 0);

```
There are a dozen cases like this to be patched.

With this fix along with one disabling xmalloc (#5), the system now only aborts over 4 of the 500+ test files from the test suite. (About 100 of the tests abort due to this initialization bug.)

**Comment by clarity20** [comment]
No longer seeing a crash on redirections in the test suite. Thanks for the tip.
